# bumpversion.ps1 - auto-increment the build number and generate version files.
#
#   reads/increments : build.number
#   writes           : uVersion.inc        (Pascal consts, included by uMain.pas)
#                      DeskTilerVersion.rc (VERSIONINFO, included by DeskTiler.rc)
#
# Every generated file is pure ASCII with no BOM, so dcc32 and brcc32 read them
# safely regardless of the system code page. Do not edit the generated files.

param([string]$Root = "")

if ($Root -eq "") {
    $Root = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
}

$ascii = New-Object System.Text.ASCIIEncoding

# ---- build number ----------------------------------------------------------
$numFile = Join-Path $Root "build.number"
$n = 0
if (Test-Path $numFile) {
    $txt = (Get-Content $numFile -Raw).Trim()
    if ($txt -match '^\d+$') { $n = [int]$txt }
}
$n = $n + 1
[System.IO.File]::WriteAllText($numFile, "$n`r`n", $ascii)

$major = 1
$minor = 0
$ver   = "$major.$minor.$n"
$stamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")

# ---- Pascal version constants ---------------------------------------------
$inc = @"
{ Generated by build.cmd (tools/bumpversion.ps1). DO NOT EDIT. }
const
  APP_VER_MAJOR   = $major;
  APP_VER_MINOR   = $minor;
  APP_VER_BUILD   = $n;
  APP_VER_STR     = '$ver';
  APP_BUILD_STAMP = '$stamp';
"@
[System.IO.File]::WriteAllText((Join-Path $Root "uVersion.inc"), $inc, $ascii)

# ---- Win32 version resource ------------------------------------------------
$rc = @"
// Generated by build.cmd (tools/bumpversion.ps1). DO NOT EDIT.
1 VERSIONINFO
 FILEVERSION    $major,$minor,$n,0
 PRODUCTVERSION $major,$minor,$n,0
 FILEOS 0x40004L
 FILETYPE 0x1L
{
  BLOCK "StringFileInfo"
  {
    BLOCK "040904B0"
    {
      VALUE "CompanyName", "DeskTiler\0"
      VALUE "FileDescription", "DeskTiler - evenly tile open application windows on the desktop\0"
      VALUE "FileVersion", "$ver\0"
      VALUE "InternalName", "DeskTiler\0"
      VALUE "LegalCopyright", "Copyright (C) rulioo   wx:rulioo521235\0"
      VALUE "OriginalFilename", "DeskTiler.exe\0"
      VALUE "ProductName", "DeskTiler\0"
      VALUE "ProductVersion", "$ver\0"
      VALUE "BuildStamp", "$stamp\0"
    }
  }
  BLOCK "VarFileInfo"
  {
    VALUE "Translation", 0x0409, 1200
  }
}
"@
[System.IO.File]::WriteAllText((Join-Path $Root "DeskTilerVersion.rc"), $rc, $ascii)

Write-Output "DeskTiler version $ver   (build $n, $stamp)"
